In [1]:
### Resource: https://www.youtube.com/watch?v=G_UYXzGuqvM&t=564s
import numpy as np

sudoku = np.matrix([[5, 3, 0,    0, 7, 0,    0, 0, 0],
                    [6, 0, 0,    1, 9, 5,    0, 0, 0],
                    [0, 9, 8,    0, 0, 0,    0, 6, 0],
                     
                    [8, 0, 0,    0, 6, 0,    0, 0, 3],
                    [4, 0, 0,    8, 0, 3,    0, 0, 1],
                    [7, 0, 0,    0, 2, 0,    0, 0, 6],
                     
                    [0, 6, 0,    0, 0, 0,    2, 8, 0],
                    [0, 0, 0,    4, 1, 9,    0, 0, 5],
                    [0, 0, 0,    0, 8, 0,    0, 7, 9]])

####### DETERMINE IF VALUE (n) WORKS IN A SPECIFIC LOCATION ON GRID (x,y) #######
def possible_value(x, y, n):
    global sudoku
    
    ####### VALIDATE IF n DOES NOT WORK IN ANY ROW #######
    for i in range(0,9):
        if sudoku[i, y] == n:
            return False

    ####### VALIDATE IF n DOES NOT WORK IN ANY COL #######
    for i in range(0,9):
        if sudoku[x, i] == n:
            return False
    
    ####### VALIDATE IF n DOES NOT WORK IN ANY BOX #######
    xO = (x//3)*3
    yO = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if sudoku[(xO+i), (yO+i)] == n:
                return False
    
    return True        
        

def solve():
    global sudoku
    for x in range(9):
        for y in range(9):
            if sudoku[x, y] == 0:
                #print(str(x)+' '+str(y))
                for n in range(1,10):
                    #print(str(x)+' '+str(y)+' '+str(n))
                    if possible_value(x, y, n):
                        sudoku[x, y]=n
                        solve()
                        sudoku[x, y]=0
                        
                return
    print(sudoku)
    print(' ')
print(sudoku) 
print(' ')
solve()


[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]
 
[[5 3 2 6 7 4 9 1 8]
 [6 7 3 1 9 5 8 4 2]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 4 9 2 8 3 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
 
[[5 3 4 6 7 2 1 9 8]
 [6 2 3 1 9 5 8 4 7]
 [3 9 8 7 4 1 5 6 2]
 [8 1 9 2 6 4 7 5 3]
 [4 7 6 8 5 3 9 2 1]
 [7 4 5 9 2 8 3 1 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [1 5 2 3 8 6 4 7 9]]
 
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
 
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 4 1 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 4 3 9 2 1 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 1 5 2 8 6 4 7 9]]
 


In [201]:
output2 = output.copy()
for point in options_list:
    try output2[point[0][0], point[0][1]] = 
    
    

SyntaxError: invalid syntax (<ipython-input-201-f2b9db437b47>, line 3)